# Archivo intencionalmente vacio.
# Para activar patrocinio en GitHub Sponsors, descomenta la linea
# correspondiente al plataforma que uses y rellena con tu username.
#
# github: [mauricioFCC]
# patreon: username
# open_collective: swarmind
# custom: ["https://buymeacoffee.com/mauriciofcc"]
