"""
install_hooks.py — Git pre-commit hook installer for the Agentic Harness.

Installs a pre-commit hook that automatically runs a lightweight
end-of-iteration pipeline on staged files.

Usage:
    python harness/scripts/install_hooks.py --install     # Install hook
    python harness/scripts/install_hooks.py --uninstall   # Uninstall hook
    python harness/scripts/install_hooks.py --status      # Show hook status
"""
from __future__ import annotations

import argparse
import os
import shutil
import stat
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

HERE = Path(__file__).resolve().parent
HARNESS_ROOT = HERE.parent
PROJECT_ROOT = HARNESS_ROOT.parent

HOOKS_DIR = Path(PROJECT_ROOT) / ".git" / "hooks"
HOOK_PATH = HOOKS_DIR / "pre-commit"
BACKUP_PATH = HOOKS_DIR / "pre-commit.agentic.bak"
STATUS_PATH = PROJECT_ROOT / "harness" / "db" / ".hook_status.json"

HOOK_TEMPLATE = r'''#!/usr/bin/env python
"""Agentic Harness - Pre-commit hook (auto-generated by install_hooks.py).
Runs a lightweight end-of-iteration pipeline on staged files.

Phases (fast, <5s):
  1. Bug hunting - staged files only
  2. Security scan - staged files only
  3. Token report - quick estimation

If CRITICAL bugs or SECRETS found: abort commit with instructions.
If MINOR issues: warn but allow commit (use --no-verify to skip).
Timeout: 5 seconds. If exceeded, allow commit and log warning.
"""
import os
import subprocess
import sys
import time
from pathlib import Path

# Hook is at .git/hooks/pre-commit, project root is 2 levels up
_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent.parent

sys.path.insert(0, str(_PROJECT_ROOT))

def _run_pre_commit():
    start = time.time()
    timeout = 5.0

    # Path to the end_of_iteration script
    eoi_script = _PROJECT_ROOT / "harness" / "scripts" / "end_of_iteration.py"
    if not eoi_script.exists():
        print("[pre-commit] end_of_iteration.py not found, skipping.")
        return 0

    # Run the pre-commit pipeline
    try:
        result = subprocess.run(
            [sys.executable, str(eoi_script), "--pre-commit"],
            capture_output=True,
            text=True,
            timeout=timeout,
            cwd=str(_PROJECT_ROOT),
        )
    except subprocess.TimeoutExpired:
        print("[pre-commit] Timeout (>5s). Allowing commit.")
        print("[pre-commit] Run `python harness/scripts/end_of_iteration.py` separately.")
        return 0
    elapsed = time.time() - start

    # Print output (but not excessively)
    for line in result.stdout.splitlines():
        print("[pre-commit]", line)
    for line in result.stderr.splitlines():
        print("[pre-commit]", line)

    if result.returncode == 0:
        print("[pre-commit] OK ({:.2f}s)".format(elapsed))
        return 0
    elif result.returncode == 2:
        # Warnings only - allow commit
        print("[pre-commit] Warnings found ({:.2f}s). Use --no-verify to skip.".format(elapsed))
        return 0
    else:
        # Critical issues - abort
        print("[pre-commit] CRITICAL issues found ({:.2f}s). Aborting commit.".format(elapsed))
        print("[pre-commit] Fix issues or use `git commit --no-verify` to skip.")
        return 1

if __name__ == "__main__":
    try:
        exit_code = _run_pre_commit()
        sys.exit(exit_code)
    except Exception as e:
        print("[pre-commit] Error: {}. Allowing commit.".format(e))
        sys.exit(0)
'''

# ANSI colours
_RED = "\033[91m"
_GREEN = "\033[92m"
_YELLOW = "\033[93m"
_CYAN = "\033[96m"
_BOLD = "\033[1m"
_RESET = "\033[0m"


def _ok(msg: str) -> str:
    return f"{_GREEN}{msg}{_RESET}"


def _warn(msg: str) -> str:
    return f"{_YELLOW}{msg}{_RESET}"


def _err(msg: str) -> str:
    return f"{_RED}{msg}{_RESET}"


def _bold(msg: str) -> str:
    return f"{_BOLD}{msg}{_RESET}"


def _cyan(msg: str) -> str:
    return f"{_CYAN}{msg}{_RESET}"


def _safe_print(*args, **kwargs) -> None:
    """Print with Unicode fallback: replaces non-encodable chars."""
    try:
        print(*args, **kwargs)
    except UnicodeEncodeError:
        safe_args = []
        for arg in args:
            if isinstance(arg, str):
                arg = (arg.replace("\u2014", "--")
                       .replace("\u2013", "-")
                       .replace("\u2500", "-")
                       .replace("\u2502", "|")
                       .replace("\u2018", "'")
                       .replace("\u2019", "'")
                       .replace("\u201c", '"')
                       .replace("\u201d", '"')
                       .replace("\u2026", "...")
                       .replace("\u00a0", " "))
            safe_args.append(arg)
        print(*safe_args, **kwargs)


def _is_git_repo() -> bool:
    """Check if the current directory is a git repository."""
    return (PROJECT_ROOT / ".git").is_dir()


def _save_status(installed: bool, timestamp: str = "") -> None:
    """Save hook installation status to JSON file."""
    import json
    status_dir = STATUS_PATH.parent
    status_dir.mkdir(parents=True, exist_ok=True)
    status = {
        "installed": installed,
        "timestamp": timestamp or datetime.now(timezone.utc).isoformat(),
        "hook_path": str(HOOK_PATH),
    }
    with open(STATUS_PATH, "w", encoding="utf-8") as f:
        json.dump(status, f, indent=2)


def _load_status() -> dict:
    """Load hook installation status from JSON file."""
    import json
    if not STATUS_PATH.exists():
        return {"installed": False, "timestamp": "", "hook_path": str(HOOK_PATH)}
    try:
        with open(STATUS_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except (json.JSONDecodeError, Exception):
        return {"installed": False, "timestamp": "", "hook_path": str(HOOK_PATH)}


def _get_last_run_info() -> Optional[str]:
    """Get the last pre-commit hook execution time from git reflog."""
    try:
        result = subprocess.run(
            ["git", "log", "--oneline", "-1", "--format=%ci", "--", ".git/hooks/pre-commit"],
            capture_output=True,
            text=True,
            timeout=10,
            cwd=str(PROJECT_ROOT),
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
    except Exception:
        pass
    return None


def install_hook() -> bool:
    """Install the pre-commit hook."""
    if not _is_git_repo():
        print(f"  {_err('[ERROR]')} No es un repositorio Git: {PROJECT_ROOT}")
        return False

    # Ensure hooks directory exists
    HOOKS_DIR.mkdir(parents=True, exist_ok=True)

    # Backup existing hook
    if HOOK_PATH.exists():
        if not BACKUP_PATH.exists():
            shutil.copy2(str(HOOK_PATH), str(BACKUP_PATH))
            _safe_print(f"  {_ok('[OK]')} Hook anterior respaldado: {BACKUP_PATH}")
        else:
            _safe_print(f"  {_warn('[WARN]')} Backup ya existe: {BACKUP_PATH}")
    else:
        _safe_print(f"  {_ok('[OK]')} No habia hook previo.")

    # Write new hook
    try:
        with open(HOOK_PATH, "w", encoding="utf-8", newline="\n") as f:
            f.write(HOOK_TEMPLATE)
        # Make executable on Unix
        if sys.platform != "win32":
            st = os.stat(HOOK_PATH)
            os.chmod(HOOK_PATH, st.st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        _save_status(True)
        _safe_print(f"  {_ok('[OK]')} Hook pre-commit instalado: {HOOK_PATH}")
        _safe_print()
        _safe_print(f"  {_bold('Hook instalado. Proximo commit ejecutara:')}")
        _safe_print(f"    {_bold('  [Bug hunting]')} -> critical? aborta")
        _safe_print(f"    {_bold('  [Security scan]')} -> secrets? aborta")
        _safe_print(f"    {_bold('  [Token report]')} -> muestra estimacion")
        _safe_print()
        _safe_print(f"  Para saltar el hook: git commit --no-verify")
        return True
    except Exception as exc:
        _safe_print(f"  {_err('[ERROR]')} No se pudo escribir el hook: {exc}")
        return False


def uninstall_hook() -> bool:
    """Uninstall the pre-commit hook and restore backup if available."""
    if not _is_git_repo():
        print(f"  {_err('[ERROR]')} No es un repositorio Git: {PROJECT_ROOT}")
        return False

    if not HOOK_PATH.exists() and not BACKUP_PATH.exists():
        _safe_print(f"  {_warn('[WARN]')} No hay hook instalado ni backup.")
        _save_status(False)
        return True

    # Check if the hook is ours (contains the agentic marker)
    if HOOK_PATH.exists():
        content = HOOK_PATH.read_text(encoding="utf-8", errors="ignore")
        is_ours = "Agentic Harness" in content
        if not is_ours:
            _safe_print(f"  {_warn('[WARN]')} El hook actual no fue instalado por Agentic Harness.")
            _safe_print(f"  {_warn('[WARN]')} No se modificara. Backup: {BACKUP_PATH}")
            return False
    else:
        is_ours = False

    # Restore backup
    if BACKUP_PATH.exists():
        shutil.copy2(str(BACKUP_PATH), str(HOOK_PATH))
        BACKUP_PATH.unlink()
        _safe_print(f"  {_ok('[OK]')} Hook original restaurado desde backup.")
    elif is_ours:
        HOOK_PATH.unlink()
        _safe_print(f"  {_ok('[OK]')} Hook Agentic eliminado (no habia backup previo).")
    else:
        _safe_print(f"  {_ok('[OK]')} No habia hook que desinstalar.")

    _save_status(False)
    _safe_print(f"  {_ok('[OK]')} Hook desinstalado exitosamente.")
    return True


def show_status() -> None:
    """Display the current hook installation status."""
    status = _load_status()
    installed = status.get("installed", False)

    hook_exists = HOOK_PATH.exists()
    hook_is_ours = False
    if hook_exists:
        content = HOOK_PATH.read_text(encoding="utf-8", errors="ignore")
        hook_is_ours = "Agentic Harness" in content

    backup_exists = BACKUP_PATH.exists()
    is_git = _is_git_repo()

    print()
    _safe_print(f"  {_bold('Estado del Hook Pre-Commit')}")
    _safe_print(f"  {'-' * 50}")

    if not is_git:
        _safe_print(f"  {_err('[ERROR]')} No es un repositorio Git.")
        return

    if hook_exists and hook_is_ours:
        _safe_print(f"  Estado:   {_ok('INSTALADO')} (Agentic Harness)")
    elif hook_exists and not hook_is_ours:
        _safe_print(f"  Estado:   {_warn('OTRO HOOK')} (no Agentic)")
    else:
        _safe_print(f"  Estado:   {_cyan('NO INSTALADO')}")

    _safe_print(f"  Ruta:     {HOOK_PATH}")
    _safe_print(f"  Backup:   {'SI' if backup_exists else 'NO'}")
    _safe_print(f"  Git repo: {'SI' if is_git else 'NO'}")

    last_run = _get_last_run_info()
    if last_run:
        _safe_print(f"  Ultimo:   {last_run}")
    elif installed:
        _safe_print(f"  Ultimo:   {_warn('Sin ejecuciones registradas')}")

    last_status_update = status.get("timestamp", "")
    if last_status_update:
        try:
            dt = datetime.fromisoformat(last_status_update)
            _safe_print(f"  Instalado: {dt.strftime('%Y-%m-%d %H:%M:%S')}")
        except (ValueError, TypeError):
            pass

    _safe_print()
    _safe_print(f"  Comandos:")
    _safe_print(f"    python harness/scripts/install_hooks.py --install")
    _safe_print(f"    python harness/scripts/install_hooks.py --uninstall")
    _safe_print(f"    python harness/scripts/install_hooks.py --status")
    _safe_print()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Install/Uninstall/Check Git pre-commit hook for Agentic Harness",
    )
    parser.add_argument("--install", action="store_true", help="Install the pre-commit hook")
    parser.add_argument("--uninstall", action="store_true", help="Uninstall the pre-commit hook")
    parser.add_argument("--status", action="store_true", help="Show hook installation status")

    args = parser.parse_args()

    if args.install:
        install_hook()
    elif args.uninstall:
        uninstall_hook()
    elif args.status:
        show_status()
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
